### ISSUE TITLE
Fix M_PI deprecated warnings

### ISSUE THREAD

**Issue by balazsgerlei** [KaiqueDamato/KDLoadingView#8]
In Xcode 8.3 this library is generating two warnings about M_PI being deprecated in Swift 3. Please change to using Double.pi (or just .pi) instead to fix these warnings.

**Comment by KaiqueDamato** [comment]
Thanks for the notice @balazsgerlei! The improvement was made! 🎉🍻

**Comment by balazsgerlei** [comment]
Cool. Thanks for the quick fix! :)
